#!/usr/bin/env bash

# Usage: use_tfenv [...]
#
# Load environment variables for a `terraform` project using `tfenv`.
# Any arguments given will be passed to `tfenv`.
#

use_tfenv() {
  return 0

	# Export terraform environent
	eval "$(tfenv)"
}
